#!/bin/sh

set -eu

# check if gh is installed
if ! command -v gh >/dev/null 2>&1; then
    echo "gh is not installed"
    exit 1
fi

if [ $# -eq 0 ]; then
sunbeam query -n '{
    title: "GitHub",
    commands: [
        {name: "search-repos", mode: "view", title: "Search Repositories"},
        {name: "list-repos", mode: "view", title: "List Repositories"},
        {name: "list-prs", mode: "view", title: "List Pull Requests", params: [{name: "repo", type: "string"}]}
    ]
}'
exit 0
fi

COMMAND=$(echo "$1" | sunbeam query -r .command)
if [ "$COMMAND" = "list-repos" ]; then
    # shellcheck disable=SC2016
    gh api "/user/repos?sort=updated" | sunbeam query '.[] |
        {
            title: .full_name,
            subtitle: (.description // ""),
            actions: [
                { title: "Open in Browser", onAction: { type: "open", target: .html_url, exit: true }},
                { title: "Copy URL", key: "o", onAction: {type: "copy",  text: .html_url, exit: true} },
                { title: "List Pull Requests", key: "p", onAction: { type: "run", command: "list-prs", params: { repo: .full_name }}}
            ]
        }
    ' | sunbeam query -s '{type: "list", items: .}'
elif [ "$COMMAND" = "search-repos" ]; then
    QUERY=$(echo "$1" | jq '.query')
    if [ "$QUERY" = "null" ]; then
        sunbeam query -n '{type: "list", reload: true, items: []}'
        exit 0
    fi

    gh api "search/repositories?q=$QUERY" | sunbeam query '.items[] |
        {
            title: .full_name,
            subtitle: (.description // ""),
            actions: [
                { title: "Open in Browser", onAction: { type: "open", target: .html_url, exit: true }},
                { title: "Copy URL", key: "o", onAction: {type: "copy",  text: .html_url, exit: true} },
                { title: "List Pull Requests", key: "p", onAction: { type: "run", command: "list-prs", params: { repo: .full_name }}}
            ]
        }
    ' | sunbeam query -s '{type: "list", reload: true, items: .}'
elif [ "$COMMAND" = "list-prs" ]; then
    REPOSITORY=$(echo "$1" | sunbeam query -r '.params.repo')
    gh pr list --repo "$REPOSITORY" --json author,title,url,number | sunbeam query '.[] |
    {
        title: .title,
        subtitle: .author.login,
        accessories: [
            "#\(.number)"
        ],
        actions: [
            {title: "Open in Browser", onAction: { type: "open", target: .url, exit: true}},
            {title: "Copy URL", key: "c", onAction: { type: "copy", text: .url, exit: true}}
        ]
    }
    ' | sunbeam query -s '{type: "list", items: .}'
fi
